### ISSUE TITLE
Image links are incorrect so pictures are missing.

### ISSUE THREAD

**Issue by farishkash** [rondoran/prj-rev-bwfs-dasmoto#1]
`<img source src="G:\Code academy\Atom\DasmotosArts&Crafts\Resources\hacksaw.jpeg">`

A couple issues here, first your image is link to your folder on your hard drive so they are missing.

Second you don't need the word **source** in your link.

Your links should use the relative path and look like this.

`<img src="./Resources/hacksaw.jpeg">`

**Comment by rondoran** [comment]
Thanks fixed the images

**Comment by rondoran** [comment]
Fixed the image links so they are now consistant
<img src="./Resources/frames.jpeg"> and they now have the same properties and work
