### ISSUE TITLE
Div structure

### ISSUE THREAD

**Issue by farishkash** [rondoran/prj-rev-bwfs-dasmoto#3]
You should have all your items in a div.  You don't have to make a div for each part if they belong together.  Also you had your pictures and h3 headings outside of your divs.

Here is your code for the paint section
```
	<div class="paint">
      <h2>Paint</h2>
    </div>
	 <img source src="G:\Code academy\Atom\DasmotosArts&Crafts\Resources\finnish.jpeg">
	<h3>Clean Finnish Paint</h3>
    <div class="p1">
        <p>Imported paint from Finland. Over 256 colors available in-store, varying in quantity (1 oz. to 8 oz.).<br> Clean Finnish paint microbinds to canvas, increasing the finish and longevity of any artwork.<br> <strong>Starting at $5.00 / tube.</strong></p>
    </div>
```

How it should be structured.

```
<div class="paint">
         <h2>Paint</h2>
	 <img source src="G:\Code academy\Atom\DasmotosArts&Crafts\Resources\finnish.jpeg">
	<h3>Clean Finnish Paint</h3>
        <p>Imported paint from Finland. Over 256 colors available in-store, varying in quantity (1 oz. 
         to 8 oz.).<br> Clean Finnish paint microbinds to canvas, increasing the finish and longevity 
         of any artwork.<br> <strong>Starting at $5.00 / tube.</strong></p>
</div>
```

**Comment by rondoran** [comment]
I have removed the <div class "p1"> to make the text consistent 
<img src="./Resources/hacksaw.jpeg">
	<h3>Hacksaw Brushes</h3>
     <p>Made of the highest quality oak, Hacksaw brushes are known for their weight and ability to hold paint in large amounts.
		<br> Available in different sizes.<br> <strong>Starting at $3.00 / brush.</strong></p>
