### ISSUE TITLE
css missing commas

### ISSUE THREAD

**Issue by farishkash** [rondoran/prj-rev-bwfs-dasmoto#4]
```
.header h1, h2, h3, p {
    font-family: Helvetica;
}

```
So you do not have a comma after .header so what you are telling the css here is that take any h1, h2, h3, p inside of the .header div and give it this font-family.  There is no h2,h3,p inside of that class so I am assuming you were trying to give them all this font-family.

If that is the case you should be writing it like this.

```
.header, h1, h2, h3, p {
    font-family: Helvetica;
}
```

The comma implies an also but when not use after the dot class name you are implying everything inside of this class that fits this criteria.

**Comment by rondoran** [comment]
Added commas and removed the p1 div as this just did not make sense
