### ISSUE TITLE
Speaking of font-family.

### ISSUE THREAD

**Issue by farishkash** [rondoran/prj-rev-bwfs-dasmoto#5]
You wrote this repetitively.

`font-family: Helvetica;`

Part of css design goals was to make it easier to write a few line of code without having to repeat yourself.  In this example since you want to target the whole page with this font all you have to do is add this to your css and you will not have to write this again.

```
body {
font-family: Helvetica;

}
```

**Comment by rondoran** [comment]
Thanks changed the CSS
